name: Cypress E2E Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install root dependencies
        run: npm ci
      - name: Start server in the background
        run: npm start &

      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: cypress
          browser: chrome
          wait-on: 'http://localhost:3000'
          config: baseUrl=http://localhost:3000
          command: npm run cypress:percy
        env:
          # pass the Percy Token
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore